name: Sample-Test

#on:
#  workflow_dispatch:
on:
  schedule:
    # Weekdays (Mon–Fri) at 1:30 PM IST (08:00 UTC)
    - cron: "0 8 * * 1-5"
    # Weekdays (Mon–Fri) at 8:30 PM IST (15:00 UTC)
    - cron: "0 15 * * 1-5"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: rapidfort/python-chromedriver

#    permissions:
#      pages: write
#      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests and generate HTML report
        run: |
          pytest practice-scripts/test_python_practice.py --html=report.html

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: html-reports
          path: |
            report.html
